### ISSUE TITLE
Delay in logging through the ZAP Hierarchial logger causes the order of logs to be mixed up

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-lib-go#11]
Observe the log below - `onos-ran` is using the k8s logger, where as ran-simulator is using the
common ZAP Hierarchial logger, while both are running on `docker-compose`.

Line 1 is the message being received by onos-ran, and Line 11 is the sending of this message by the ran-simulator. The time stamp for the sending looks right 602ms, and the receiving is at 603ms, but the order in which they are put to **Standard Out** is wrong because of a delay in processing (with the Sugared logger I expect)

```
onos-ran_1       | I0221 13:00:21.603046       1 e2.go:136] Got messageType 2
onos-ran_1       | I0221 13:00:21.603068       1 e2.go:158] plmnid:001001, ecid:0000001
onos-ran_1       | I0221 13:00:21.603090       1 e2.go:136] Got messageType 2
ran-simulator_1  | {"level":"INFO","ts":"2020-02-21T13:00:21.602Z","northbound/e2":"northbound/e2","msg":"handleCellConfigReport eci: 0000007"}
onos-ran_1       | I0221 13:00:21.603099       1 e2.go:158] plmnid:001001, ecid:0000003
ran-simulator_1  | {"level":"INFO","ts":"2020-02-21T13:00:21.602Z","northbound/e2":"northbound/e2","msg":"handleCellConfigReport eci: 0000002"}
onos-ran_1       | I0221 13:00:21.603111       1 manager.go:77] Got messageType 2
onos-ran_1       | I0221 13:00:21.603118       1 manager.go:80] plmnid:001001, ecid:0000001
onos-ran_1       | I0221 13:00:21.603126       1 manager.go:77] Got messageType 2
onos-ran_1       | I0221 13:00:21.603132       1 manager.go:80] plmnid:001001, ecid:0000003
ran-simulator_1  | {"level":"INFO","ts":"2020-02-21T13:00:21.602Z","northbound/e2":"northbound/e2","msg":"Sending control message CELL_CONFIG_REPORT"}
```

**Comment by adibrastegarnia** [comment]
@SeanCondon 
Sorry for late reply. I didn't pay attention to the issues. Suggered logger is a little bit slower but has more flexibility however, my plan is to enable standard logger as well in case we need to use it for systems that delay is super important. I think the scenario that you explained also is dependent on other factors because those subsystems are running in two different environments asynchronously and I don't think we can guarantee order of messages between two independent subsystems. In addition to that, when this experiment is done, you were using two different loggers which potentially are different in terms of performance I guess and perhaps is not a fair comparison. Since we moved to k8s and migrated all of the loggers to use the new logger, If you still think this is an issue, please feel free to reopen it. I hope I addressed your issue.

**Comment by SeanCondon** [comment]
ok
